### ISSUE TITLE
Code for invariant NFN classification

### ISSUE THREAD

**Issue by dddiowww** [AllanYangZhou/nfn#10]
Thank you for releasing the code, it's an amazing work! I'd like to ask if you released the training code for classification using NFN, corresponding to part 3.2 in the paper 'Permutation Equivariant Neural Functionals'. Thanks in advance.

**Comment by AllanYangZhou** [comment]
Hi, thanks for your interest. Will do, working on it.

**Comment by AllanYangZhou** [comment]
This is added in https://github.com/AllanYangZhou/nfn/commit/ce783221fd7c511596220d805c7a5beccd764ee8.
