### ISSUE TITLE
Code for weight space editing

### ISSUE THREAD

**Issue by adricarda** [AllanYangZhou/nfn#2]
Hi, thank you for releasing the code. Is the code for weight space editing included in this repo? even just the model would be helpful.
Thanks in advance.

**Comment by AllanYangZhou** [comment]
Just added the code (and data) for style editing: https://github.com/AllanYangZhou/nfn/tree/main/experiments#stylizing-sirens.

By model, do you mean pre-trained NFN weights? It might take me a bit, but I could probably save some trained weights and upload them.

**Comment by adricarda** [comment]
Hi Allan, amazing! thank you very much. The code is sufficient.

Best,
Adriano
