### ISSUE TITLE
Parameter sharing derivation

### ISSUE THREAD

**Issue by frallebini** [AllanYangZhou/nfn#4]
Hi,

My question is not necessarily code-related, but I think this can serve as a good platform to discuss it openly.

In appendix B.3 of the paper (arXiv preprint), equation 15 states

$[P_\sigma\theta]^\alpha_\beta=\theta_\beta^{\sigma^{-1}(\alpha)}=\theta_{\sigma(\beta)}^\alpha=[\theta P_\sigma]^\alpha_\beta$

However, I don't get the $\theta_{\sigma(\beta)}^\alpha$ part. As far as I understand, we have

$[P_\sigma\theta]^\alpha_\beta=\theta_\beta^{\sigma^{-1}(\alpha)}$
$[\theta P_\sigma]^\alpha_\beta=\theta^\alpha_{\sigma^{-1}(\beta)}$

i.e. I put $\sigma^{-1}(\beta)$ in the second equation instead of the $\sigma(\beta)$ of eq. 15. 

What am I missing?

**Comment by AllanYangZhou** [comment]
The key is the difference between left matrix multiplication and right matrix multiplication by $P_\sigma$. For simplicity let's just think of $\alpha,\beta$ as the row and column indices of a matrix.

Let's explicitly define $P_\sigma$ as being a matrix of zeroes except for $1$'s where $\alpha = \sigma(\beta) \iff \sigma^{-1}(\alpha)=\beta$:
$$[P_\sigma]^{\alpha}_\beta = \mathbb{1}\\{\alpha = \sigma(\beta)\\} = \mathbb{1}\\{\sigma^{-1}(\alpha) = \beta\\}$$

Then using the definition of matrix multiplication: $$[P_\sigma \theta]^\alpha_\beta = \sum_\gamma [P_\sigma]^\alpha_\gamma \theta^\gamma_\beta = \sum_\gamma  \mathbb{1}\\{\sigma^{-1}(\alpha) = \gamma\\} \theta^\gamma_\beta = \theta^{\sigma^{-1}(\alpha)}_\beta$$

On the other hand, for the right-matrix mult:
$$[\theta P_\sigma]^\alpha_\beta = \sum_\gamma \theta^\alpha_\gamma [P_\sigma]^\gamma_\beta = \sum_\gamma  \theta^\alpha_\gamma \mathbb{1}\\{\gamma = \sigma(\beta)\\} = \theta^\alpha_{\sigma(\beta)}$$

**Comment by frallebini** [comment]
Got it, thank you very much.
