### ISSUE TITLE
Code for the NFT paper

### ISSUE THREAD

**Issue by alexlyzhov** [AllanYangZhou/nfn#5]
The May NFT preprint links to this repo, but it seems like it only contains the NFN code. It would be great to see the NFT/INR2Array training implementation.

**Comment by AllanYangZhou** [comment]
Sorry for the delay, was traveling a bit recently. Will work on this now, and I expect at least the NFT layers themselves should be released soon.

**Comment by soubhiksanyal** [comment]
Hi, Is there any updates on releasing the NFT layers?

**Comment by AllanYangZhou** [comment]
Thanks for the patience...

I've add INR2Array, with instructions [here](https://github.com/AllanYangZhou/nfn/tree/main/experiments#with-inr2array-nft).

~I haven't updated the pip NFN package on pypi yet, so to get the NFT layers you should pip install from the github repo.~ The PyPI package has also been updated. And examples of constructing architectures using the layers [here](https://github.com/AllanYangZhou/nfn/blob/main/experiments/models.py#L382).
