### ISSUE TITLE
About the number of training images in MNIST

### ISSUE THREAD

**Issue by BannyStone** [AllanYangZhou/nfn#8]
Hi Allan,

Great work on weight space representation learning! I have a question regarding the number of training samples in MNIST. I downloaded the MNIST weights and biases from this repo. I find that there are in total of 60000 samples and only 45000 have 10 augmented copies. However, there should be 70000 in total (60000 samples for training and another 10000 for testing): https://en.wikipedia.org/wiki/MNIST_database

Do I miss anything? Looking forward to your reply!

Best

**Comment by AllanYangZhou** [comment]
Hi, thanks for your interest. I don't think you're missing anything--when generating the SIREN data, I believe I accidentally took only 60,000 images out of the 70k total. Then I split the images into [45k training, 5k val, 10k test]. So the training set size is slightly smaller than in the (image-space) version of MNIST.
